# Site settings
baseurl = "http://8-uh.github.io/"
# HTML Language Code Reference, such as en, zh-cn
languageCode = "en"
title = "love-notes"
theme = "cactus-plus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-98111565-1"
hasCJKLanguage = true


[params]
	name = "love-notes"
	description = "code doodles and diatribes"
	bio = "Algorithmic Psychonautica"
	# Enter optionally your twitter account
	twitter = "@adabeezus"
	enableRSS = true

	# Disqus comment
	disqusShortname = "love-notes"
	# Disable disqus comments by set `enableDisqus = "false"`
	enableDisqus = true

	# Duoshuo comment
	duoshuoShortname = "your_duoshuo_short_name"
	# Disable duoshuo comments by set `enableDuoshuo = "false"`
	enableDuoshuo = false

	enableGithubIssuesTips = false

	# Enable googleAnalytics
	enableGoogleAnalytics = true

	# Enable baiduAnalytics
	enableBaiduAnalytics = false
	# Baidu Tongji Code
	baiduAnalytics = 'your_baidu_tongji_code'

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = "~/"
	about = "~/about"
	archive = "~/posts"
	tags = "~/tags"
	subscribe = "./rss.sh"
	# Pagination links
	olderPosts = "previous explorations"
	newerPosts = "newer experimentations"
	readMore = "don't turn back now..."
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Algorithmic Psychonaut"
	tweet = ""
	share = ""
	# 404 page
	title404 = "nope."
	subtitle404 = "404"

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = "rounded"


# Add additional social link entries underneath
[social]
	facebook-square = "https://www.facebook.com/profile.php?id=100014010943721"
  twitter-square = "https://twitter.com/adabeezus"
  github-square = "http://github.com/8-uh"
